[project]
name = "fastapi-ecommerce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.4", # Database migration tool
    "asyncpg>=0.31.0", # Async PostgreSQL driver
    "fastapi>=0.133.1", # Web framework
    "httpx>=0.28.1", # HTTP client
    "passlib[bcrypt]>=1.7.4", # Password hashing
    "pydantic[email]>=2.12.5", # Data validation
    "pydantic-settings>=2.13.1", # Settings management
    "pytest>=9.0.2", # Testing framework
    "pytest-asyncio>=1.3.0", # Async testing
    "python-jose[cryptography]>=3.5.0", # JWT implementation
    "redis>=7.2.1", # Redis client
    "sqlalchemy[asyncio]>=2.0.47", # ORM
    "uvicorn[standard]>=0.41.0", # ASGI server
    "bcrypt>=5.0.0", # Password hashing
]

[project.scripts]
dev   = "app._scripts:dev"
start = "app._scripts:start"

[dependency-groups]
dev = [
    "black>=26.1.0",
    "mypy>=1.19.1",
    "ruff>=0.15.4",
]